version: "3.8"

x-backend-base: &be-base
  build:
    context: ./backend
  restart: always
  networks:
    - infra
    - internal
  depends_on:
    - postgres
    - redis
  env_file:
    - ${ENV_FILE:-./backend/.env.local}

services:
  frontend:
    build:
      context: ./frontend
      args:
        ENVIRONMENT: "${ENV:-local-backend}"
    restart: always
    ports:
      - "5173:80"
    networks:
      - infra

  persister:
    <<: *be-base
    image: persiser
    command: ["persister", "listen"]
    ports:
      - "8081:8081"

  proxier:
    <<: *be-base
    image: proxier
    command: [ "proxier", "listen" ]
    ports:
      - "8082:8082"

  postgres:
    image: postgres:latest
    restart: always
    networks:
      - internal
    environment:
      POSTGRES_USER: ${PG_USER:-hpdb}
      POSTGRES_PASSWORD: ${PG_PWD:-hpdb}
      POSTGRES_DB: ${PG_DB:-hpdb}

  redis:
    image: redis:latest
    restart: always
    networks:
      - internal

networks:
  infra:
  internal:
